= Prayers

******
These are prayers taked from the _Compendiudm of the Catechism of the Catholic Church_.
There are basic prayers, prayers to your guardian angel, for the dead, etc.
******

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Our Father*|*Pater Noster*

|Our Father who art in heaven,
hallowed be thy name.
Thy kingdom come.
Thy will be done 
on earth, as it is in heaven.
Give us this day 
our daily bread,
and forgive us our trespasses, 
as we forgive those who trespass against us,
and lead us not into temptation,
but deliver us from evil.

|Pater noster, qui es in cælis:
sanctificétur Nomen Tuum:
advéniat Regnum Tuum:
fiat volúntas Tua,
sicut in cælo, et in terra.
Panem nostrum 
cotidiánum da nobis hódie,
et dimítte nobis débita nostra,  
sicut et nos 
dimíttimus debitóribus nostris.
et ne nos indúcas in tentatiónem; 
sed líbera nos a Malo.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Sign of the Cross* | *Signum Crucis*
|In the name of the Father
and of the Son
and of the Holy Spirit. Amen.

|  In nómine Patris
et Fílii
et Spíritus Sancti. Amen.
|=======


[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Glory be to the Father* |*Gloria Patri*
|Glory be to the Father
and to the Son
and to the Holy Spirit,
as it was in the beginning
is now, and ever shall be
world without end. Amen.

|Glória Patri
et Fílio
et Spirítui Sancto.
Sicut erat in princípio,
et nunc et semper
et in sæcula sæculórum. Amen.
|=======
 

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Hail Mary* |*Ave, Maria*
|Hail, Mary, full of grace,
the Lord is with thee.
Blessed art thou among women
and blessed is the fruit of thy womb, Jesus.
Holy Mary, Mother of God,
pray for us sinners,
now and at the hour of our death. 
Amen.

|Ave, María, grátia plena,
Dóminus tecum.
Benedícta tu in muliéribus,
et benedíctus fructus ventris tui, Iesus.
Sancta María, Mater Dei,
ora pro nobis peccatóribus,
nunc et in hora mortis nostræ.
Amen.
|=======


[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Angel of God*|*Angele Dei*
|Angel of God, 
my guardian dear,
to whom God’s love commits me here,
ever this day be at my side,
to light and guard, to rule and guide. 
Amen.

|Ángele Dei,
qui custos es mei,
me, tibi commíssum pietáte supérna,
illúmina, custódi,
rege et gubérna.
Amen.
|=======


[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Eternal Rest*|*Requiem Æternam*
|Eternal rest grant unto them, O Lord,
and let perpetual light shine upon them.
May they rest in peace. Amen.

|Réquiem ætérnam dona eis, Dómine,
et lux perpétua lúceat eis.
Requiéscant in pace. Amen.
|=======
 

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Angelus*|*Angelus Domini*
| V. The Angel of the Lord declared unto Mary. +
 R. And she conceived of the Holy Spirit. +

Hail, Mary, full of grace, the Lord is with thee.
Blessed art thou among women,
and blessed is the fruit of thy womb, Jesus.
Holy Mary, Mother of God,
pray for us sinners,
now and at the hour of our death. Amen. +

 V. Behold the handmaid of the Lord. +
 R. Be it done unto me according to thy word. +
Hail Mary. +

 V. And the Word was made flesh. +
 R. And dwelt among us. +
Hail Mary. +

 V. Pray for us, O holy Mother of God. +
 R. That we may be made worthy of the promises of Christ. +

Let us pray; +

Pour forth, we beseech thee, O Lord, thy grace into our hearts; that we, to
whom the Incarnation of Christ, thy Son, was made known by the message of an
angel, may by his Passion and Cross be brought to the glory of his
Resurrection. Through the same Christ, our Lord.  Amen. +

Glory be to the Father... +


|Ángelus Dómini nuntiávit Maríæ. +
Et concépit de Spíritu Sancto. +

Ave, María... +

Ecce ancílla Dómini. +
Fiat mihi secúndum verbum tuum. +

Ave, María... +

Et Verbum caro factum est. +
Et habitávit in nobis. +

Ave, María... +

Ora pro nobis, sancta Dei génetrix. +
Ut digni efficiámur promissiónibus Christi. +

Orémus. +

Grátiam tuam, quæsumus,
Dómine, méntibus nostris infúnde;
ut qui, Ángelo nuntiánte,
Christi Fílii tui incarnatiónem cognóvimus,
per passiónem eius et crucem,
ad resurrectiónis glóriam perducámur.

Per eúndem Christum Dóminum nostrum. Amen. +

Glória Patri... +
|=======


[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Regina Caeli*|*Regina Cæli*
|Queen of heaven, rejoice, alleluia.
The Son whom you merited to bear, alleluia,
has risen as he said, alleluia.
Rejoice and be glad, O Virgin Mary, alleluia!
For the Lord has truly risen, alleluia. +
 +
Let us pray; +
 +
O God, who through the resurrection of your Son, our Lord Jesus Christ, did vouchsafe to give joy to the world; grant, we beseech you, that through his Mother, the Virgin Mary, we may obtain the joys of everlasting life. Through the same Christ our Lord. Amen.

|Regína cæli lætáre, allelúia.
Quia quem meruísti portáre, allelúia. +
 +
Resurréxit, sicut dixit, allelúia.
Ora pro nobis Deum, allelúia. +
 +
Gaude et lætáre, Virgo María, allelúia.
Quia surréxit Dóminus vere, allelúia. +
 +
Orémus. +
 +
Deus, qui per resurrectiónem Fílii tui Dómini nostri Iesu Christi mundum lætificáre dignátus es, præsta, quæsumus, ut per eius Genetrícem Vírginem Maríam perpétuæ capiámus gáudia vitæ.
Per Christum Dóminum nostrum. Amen.
|=======


[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Hail Holy Queen*|*Salve, Regina*
|Hail, Holy Queen, Mother of Mercy, 
Hail our life, our sweetness and our hope! 
To thee do we cry, poor banished children of Eve.
To thee do we send up our sighs, mourning and weeping
 in this valley of tears! Turn, then, most gracious Advocate, 
thine eyes of mercy toward us, 
and after this, our exile,
show unto us the blessed fruit of thy womb, Jesus. 
O clement, O loving, 
O sweet Virgin Mary. +

|Salve, Regína,
Mater misericórdiæ,
vita, dulcédo et spes nostra, salve.
Ad te clamámus,
éxsules fílii Evæ.
Ad te suspirámus geméntes et flentes
in hac lacrimárum valle.
Eia ergo, advocáta nostra,
illos tuos misericórdes óculos 
ad nos convérte.
Et Iesum benedíctum fructum ventris tui,
nobis, post hoc exsílium, osténde.
O clemens, o pia, o dulcis Virgo María!
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Magnificat*|*Magnificat*
|My soul proclaims the greatness of the Lord,
my spirit rejoices in God my Savior,
for he has looked with favor on his lowly servant.
From this day all generations will call me blessed:
the Almighty has done great things for me,
and holy is his Name.
He has mercy on those who fear him 
in every generation.
He has shown the strength of his arm,
he has scattered the proud in their conceit.
He has cast down the mighty from their thrones,
and has lifted up the lowly.
He has filled the hungry with good things,
and the rich he has sent away empty.
He has come to the help of his servant Israel
for he has remembered his promise of mercy,
the promise he made to our fathers,
to Abraham and his children forever.
Glory to the Father and to the Son and to the Holy Spirit,
as it was in the beginning, is now, and will be forever. Amen.


|Magníficat ánima mea Dóminum,
et exsultávit spíritus meus
in Deo salvatóre meo,
quia respéxit humilitátem
ancíllæ suæ.

Ecce enim ex hoc beátam
me dicent omnes generatiónes,
quia fecit mihi magna,
qui potens est,
et sanctum nomen eius,
et misericórdia eius in progénies
et progénies timéntibus eum.
Fecit poténtiam in bráchio suo,
dispérsit supérbos mente cordis sui;
depósuit poténtes de sede
et exaltávit húmiles.
Esuriéntes implévit bonis
et dívites dimísit inánes.
Suscépit Ísrael púerum suum,
recordátus misericórdiæ,
sicut locútus est ad patres nostros,
Ábraham et sémini eius in sæcula.
Glória Patri et Fílio
et Spirítui Sancto.
Sicut erat in princípio,
et nunc et semper,
et in sæcula sæculórum.
Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Under Your Protection*|*Sub tuum præsidium*
|We fly to thy protection, 
O holy Mother of God.
Despise not our petitions 
in our necessities,
but deliver us always 
from all dangers
O glorious and blessed Virgin.

|Sub tuum præsídium confúgimus,
sancta Dei Génetrix;
nostras deprecatiónes ne despícias
in necessitátibus;
sed a perículis cunctis
líbera nos semper,
Virgo gloriósa et benedícta.
|=======

   

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Benedictus*|*Benedictus*
|Blessed be the Lord, the God of Israel;
he has come to his people and set them free.
He has raised up for us a mighty savior,
born of the house of his servant David.
Through his holy prophets he promised of old
that he would save us from our enemies,
from the hands of all who hate us.
He promised to show mercy to our fathers
and to remember his holy covenant.
This was the oath he swore to our father
Abraham:
to set us free from the hands of our enemies,
free to worship him without fear,
holy and righteous in his sight all the days of our life.
You, my child, shall be called the prophet of the Most High;
for you will go before the Lord to prepare his way,
to give his people knowledge of salvation 
by the forgiveness of their sins.
In the tender compassion of our God
the dawn from on high shall break upon us,
to shine on those who dwell in darkness and the shadow of death,
and to guide our feet into the way of peace.
Glory to the Father and to the Son and to the Holy Spirit,
as it was in the beginning, is now, and will be forever. Amen.

|Benedíctus Dóminus, Deus Ísrael,
quia visitávit
et fecit redemptiónem plebi suæ,
et eréxit cornu salútis nobis
in domo David púeri sui,
sicut locútus est per os sanctórum,
qui a sæculo sunt, prophetárum eius,
salútem ex inimícis nostris
et de manu ómnium,
qui odérunt nos;
ad faciéndam misericórdiam
cum pátribus nostris
et memorári testaménti sui sancti,
iusiurándum, quod iurávit
ad Ábraham patrem nostrum,
datúrum se nobis,
ut sine timóre,
de manu inimicórum liberáti,
serviámus illi
in sanctitáte et iustítia coram ipso
ómnibus diébus nostris.
Et tu, puer,
prophéta Altíssimi vocáberis:
præíbis enim ante fáciem Dómini
paráre vias eius,
ad dandam sciéntiam salútis
plebi eius
in remissiónem peccatórum eórum,
per víscera misericórdiæ Dei nostri,
in quibus visitábit nos óriens ex alto,
illumináre his, qui in ténebris
et in umbra mortis sedent,
ad dirigéndos pedes nostros
in viam pacis.
Glória Patri et Fílio
et Spirítui Sancto.
Sicut erat in princípio,
et nunc
et semper,
et in sæcula sæculórum. Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Te Deum*|*Te Deum*
|You are God: we praise you;
You are God: we acclaim you;
You are the eternal Father:
All creation worships you.
To you all angels, all the powers of heaven,
Cherubim and Seraphim, sing in endless praise:
Holy, holy, holy, Lord, God of power and might,
Heaven and earth are full of your glory.
The glorious company of apostles praise you.
The noble fellowship of prophets praise you.
The white-robed army of martyrs praise you.
Throughout the world the holy Church acclaims you:
Father, of majesty unbounded,
Your true and only Son, worthy of all worship,
And the Holy Spirit, advocate and guide.
You, Christ, are the king of glory,
The eternal Son of the Father.
When you became man to set us free
You did not spurn the Virgin’s womb.
You overcame the sting of death,
And opened the kingdom of heaven to all believers.
You are seated at God’s right hand in glory.
We believe that you will come, and be our judge.
Come then, Lord, and help your people,
Bought with the price of your own blood,
And bring us with your saints
To glory everlasting.
Save your people, Lord, and bless your inheritance.
Govern and uphold them now and always.
Day by day we bless you.
We praise your name forever.
Keep us today, Lord, from all sin.
Have mercy on us, Lord, have mercy.
Lord, show us your love and mercy;
For we put our trust in you.
In you, Lord, is our hope:
And we shall never hope in vain.

|Te Deum laudámus:
te Dóminum confitémur.
Te ætérnum Patrem,
omnis terra venerátur.
tibi omnes ángeli,
tibi cæli et univérsæ potestátes:
tibi chérubim et séraphim
incessábili voce proclámant:
Sanctus, Sanctus, Sanctus,
Dóminus Deus Sábaoth.
Pleni sunt cæli et terra
maiestátis glóriæ tuæ.
Te gloriósus
apostolórum chorus,
te prophetárum
laudábilis númerus,
te mártyrum candidátus
laudat exércitus.
Te per orbem terrárum
sancta confitétur Ecclésia,
Patrem imménsæ maiestátis;
venerándum tuum verum
et únicum Fílium;
Sanctum quoque
Paráclitum Spíritum.
Tu rex glóriæ, Christe.
Tu Patris sempitérnus es Fílius.
Tu, ad liberándum susceptúrus
hóminem,
non horruísti Vírginis úterum.
Tu, devícto mortis acúleo,
aperuísti credéntibus regna cælórum.
Tu ad déxteram Dei sedes,
in glória Patris.
Iudex créderis esse ventúrus.
Te ergo quæsumus,
tuis fámulis súbveni,
quos pretióso sánguine redemísti.
Ætérna fac cum sanctis tuis
in glória numerári.
Salvum fac pópulum tuum, Dómine,
et bénedic hereditáti tuæ.
Et rege eos, et extólle illos
usque in ætérnum.
Per síngulos dies benedícimus te;
et laudámus nomen tuum
in sæculum, et in sæculum sæculi.
Dignáre, Dómine,
die isto sine peccáto nos custodíre.
Miserére nostri, Dómine, miserére nostri.
Fiat misericórdia tua,
Dómine, super nos,
quemádmodum sperávimus in te.
In te, Dómine, sperávi:
non confúndar in ætérnum.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Come, Creator Spirit*|*Veni, Creator Spiritus*
|Come, Holy Spirit, Creator come, 
From your bright heavenly throne!
Come, take possession of our souls, 
And make them all your own.
You who are called the Paraclete,
Best gift of God above,
The living spring, the living fire, 
Sweet unction, and true love!
You who are sevenfold in your grace, 
Finger of God's right hand,
His promise, teaching little ones
To speak and understand!
O guide our minds with your blessed light, 
With love our hearts inflame,
And with your strength which never decays
Confirm our mortal frame.
Far from us drive our hellish foe 
True peace unto us bring,
And through all perils guide us safe
Beneath your sacred wing.
Through you may we the Father know,
Through you the eternal Son
And you the Spirit of them both
Thrice-blessed three in one.
All glory to the Father be,
And to the risen Son;
The same to you, O Paraclete,
While endless ages run. Amen.

|Veni, creátor Spíritus,
mentes tuórum vísita,
imple supérna grátia,
quæ tu creásti péctora.
Qui díceris Paráclitus,
altíssimi donum Dei,
fons vivus, ignis, cáritas,
et spiritális únctio.
Tu septifórmis múnere,
dígitus patérnæ déxteræ,
tu rite promíssum Patris,
sermóne ditans gúttura.
Accénde lumen sénsibus,
infúnde amórem córdibus,
infírma nostri córporis
virtúte firmans pérpeti.
Hostem repéllas lóngius
pacémque dones prótinus;
ductóre sic te prævio
vitémus omne nóxium.
Per Te sciámus da Patrem
noscámus atque Fílium,
teque utriúsque Spíritum
credámus omni témpore.
Deo Patri sit glória,
et Fílio, qui a mórtuis
surréxit, ac Paráclito,
in sæculórum sæcula. Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Come, Holy Spirit*|*Veni, Sancte Spiritus*
|Come, Holy Spirit, come!
And from your celestial home
Shed a ray of light divine!
Come, Father of the poor!
Come, source of all our store!
Come, within our bosoms shine.
You, of comforters the best;
You, the soul’s most welcome guest;
Sweet refreshment here below;
In our labor, rest most sweet;
Grateful coolness in the heat;
Solace in the midst of woe.
O most blessed Light divine,
Shine within these hearts of yours,
And our inmost being fill!
Where you are not, we have naught,
Nothing good in deed or thought,
Nothing free from taint of ill.
Heal our wounds, our strength renew;
On our dryness pour your dew;
Wash the stains of guilt away:
Bend the stubborn heart and will;
Melt the frozen, warm the chill;
Guide the steps that go astray.
On the faithful, who adore
And confess you, evermore 
In your sevenfold gift descend:
Give them virtue’s sure reward;
Give them your salvation, Lord;
Give them joys that never end.

|Veni, Sancte Spíritus,
et emítte cælitus
lucis tuæ rádium.
Veni, pater páuperum,
veni, dator múnerum,
veni, lumen córdium.
Consolátor óptime,
dulcis hospes ánimæ,
dulce refrigérium.
In labóre réquies,
in æstu tempéries,
in fletu solácium.
O lux beatíssima,
reple cordis íntima
tuórum fidélium.
Sine tuo númine,
nihil est in hómine
nihil est innóxium.
Lava quod est sórdidum,
riga quod est áridum,
sana quod est sáucium.
Flecte quod est rígidum,
fove quod est frígidum,
rege quod est dévium.
Da tuis fidélibus,
in te confidéntibus,
sacrum septenárium.
Da virtútis méritum,
da salútis éxitum,
da perénne gáudium. Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Anima Christi*|*Anima Christi*
|Soul of Christ, be my sanctification.
Body of Christ, be my salvation.
Blood of Christ, fill all my veins.
Water of Christ’s side, wash out my stains.
Passion of Christ, my comfort be.
O good Jesus, listen to me.
In Thy wounds I fain would hide,
N’er to be parted from Thy side,
Guard me, should the foe assail me.
Call me when my life shall fail me.
Bid me come to Thee above,
With Thy saints to sing Thy love,
World without end. Amen.

|Ánima Christi, sanctífica me.
Corpus Christi, salva me.
Sanguis Christi, inébria me.
Aqua láteris Christi, lava me.
Pássio Christi, confórta me.
O bone Iesu, exáudi me.
Intra tua vúlnera abscónde me.
Ne permíttas me separári a te.
Ab hoste malígno defénde me.
In hora mortis meæ voca me.
Et iube me veníre ad te,
ut cum Sanctis tuis laudem te
in sæcula sæculórum. Amen
|=======

 

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Memorare*|*Memorare*
|Remember, O most gracious Virgin Mary,
that never was it known 
that anyone who fled to thy protection, 
implored thy help, 
or sought thy intercession, 
was left unaided. 
Inspired by this confidence 
I fly unto thee, 
O Virgin of virgins, my Mother. 
To thee do I come, 
before thee I stand, 
sinful and sorrowful. 
O Mother of the Word Incarnate,
despise not my petitions, 
but in thy mercy hear and answer me. 
Amen.

|Memoráre, o piíssima Virgo María, 
non esse audítum a sæculo, 
quemquam ad tua curréntem præsídia,
tua implorántem auxília, 
tua peténtem suffrágia, esse derelíctum. 
Ego tali animátus confidéntia, 
ad te, Virgo Vírginum, Mater, 
curro, ad te vénio, 
coram te gemens peccátor assísto. 
Noli, Mater Verbi, verba mea despícere; 
sed áudi propítia et exáudi. Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*The Rosary*|*Rosarium*
|The Joyful Mysteries
(recited Monday and Saturday)

The Annunciation
The Visitation
The Nativity
The Presentation
The Finding in the Temple

 

The Mysteries of Light
(recited Thursday)

The Baptism of Jesus
The Wedding Feast of Cana
The Proclamation of the Kingdom, with the call to Conversion
The Transfiguration
The Institution of the Eucharist

 

The Sorrowful Mysteries
(recited Tuesday and Friday)

The Agony in the Garden
The Scourging at the Pillar
The Crowning with Thorns
The Carrying of the Cross
The Crucifixion

 

The Glorious Mysteries 
(recited Wednesday and Sunday)

The Resurrection 
The Ascension
The Descent of the Holy Spirit
The Assumption
The Coronation of Mary Queen of Heaven and Earth

 

Prayer concluding the Rosary

Hail, Holy Queen, etc. as above

 V. Pray for us, O holy Mother of God.
 R. That we may be made worthy of the promises of Christ.

 

Let us pray.

O God, whose only-begotten Son, 
by his life, death and resurrection, 
has purchased for us 
the rewards of eternal life, 
grant, we beseech thee, 
that meditating on these mysteries
of the most holy Rosary of the 
Blessed Virgin Mary, 
we may imitate what they contain 
and obtain what they promise, 
through the same Christ our Lord. 
Amen.

|Mystéria gaudiósa
(in feria secunda et sabbato)

Annuntiátio.
Visitátio.
Natívitas.
Præsentátio.
Invéntio in Templo.

 

Mystéria luminósa
(in feria quinta)

Baptísma apud Iordánem.
Autorevelátio apud Cananénse matrimónium.
Regni Dei proclamátio coniúncta cum invitaménto
ad conversiónem.
Transfigurátio.
Eucharístiæ Institútio.

 

Mystéria dolorósa
(in feria tertia et feria sexta)

Agonía in Hortu.
Flagellátio.
Coronátio Spinis.
Baiulátio Crucis.
Crucifíxio et Mors.

 

Mystéria gloriósa
(in feria quarta et Dominica)

Resurréctio.
Ascénsio.
Descénsus Spíritus Sancti.
Assúmptio.
Coronátio in Cælo.

 

Oratio ad finem Rosarii dicenda

Ora pro nobis, sancta Dei génetrix.
Ut digni efficiámur promissiónibus Christi.

 

Orémus.

Deus, cuius Unigénitus per vitam, 
mortem et resurrectiónem suam 
nobis salútis ætérnæ 
præmia comparávit, 
concéde, quæsumus:
ut hæc mystéria sacratíssimo 
beátæ Maríæ Vírginis 
Rosário recoléntes,
et imitémur quod cóntinent,
et quod promíttunt assequámur. 
Per Christum Dóminum nostrum. 
Amen.
|=======

[width="85%",style="verse",cols=1,options="header"]
|=======
|*Coptic Incense Prayer*
|O King of peace, give us your peace and pardon our sins. Dismiss the enemies
of the Church and protect her so that she never fail. Emmanuel our God is in
our midst in the glory of the Father and of the Holy Spirit. May he bless us
and purify our hearts and cure the sicknesses of our soul and body. We adore
you, O Christ, with your good Father and the Holy Spirit because you have come
and you have saved us.
|=======


[width="85%",style="verse",cols='.<',options="header"]
|=======
|*Syro-Maronite Farewell to the Altar*

|Remain in peace, O Altar of God. May the offering that I have taken from you be for the remission of my debts and the pardon of my sins and may it obtain for me that I may stand before the tribunal of Christ without condemnation and without confusion. I do not know if I will have the opportunity to return and offer another sacrifice upon you. Protect me, O Lord, and preserve your holy Church as the way to truth and salvation. Amen.
|=======
 

 
[width="85%",style="verse",cols='.<',options="header"]
|=======
|*Byzantine Prayer for the Deceased*

|God of the spirits and of all flesh, who have trampled death and annihilated
the devil and given life to your world, may you yourself, O Lord, grant to the
soul of your deceased servant N. rest in a place of light, a verdant place, a
place of freshness, from where suffering, pain and cries are far removed. Do
You, O good and compassionate God forgive every fault committed by him in word,
work or thought because there is no man who lives and does not sin. You alone
are without sin and your justice is justice throughout the ages and your word
is truth. Since you, O Christ our God, are the resurrection, the life and the
repose of your deceased servant N., we give you glory together with your
un-begotten Father and your most holy, good and life-creating Spirit, now and
always and forever and ever.
|=======
 

 
[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Act of Faith*|*Actus fidei*
|O my God, I firmly believe 
that you are one God in three divine Persons,
Father, Son, and Holy Spirit. 
I believe that your divine Son became man 
and died for our sins and that he will come 
to judge the living and the dead. 
I believe these and all the truths 
which the Holy Catholic Church teaches
because you have revealed them 
who are eternal truth and wisdom, 
who can neither deceive nor be deceived. 
In this faith I intend to live and die. 
Amen.

|Dómine Deus,
firma fide credo et confíteor 
ómnia et síngula quæ 
sancta Ecclésia Cathólica propónit, 
quia tu, Deus, ea ómnia revelásti, 
qui es ætérna véritas et sapiéntia 
quæ nec fállere nec falli potest.
In hac fide vívere et mori státuo. 
Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Act of Hope*|*Actus spei*
|O Lord God, 
I hope by your grace for the pardon 
of all my sins
and after life here to gain eternal happiness
because you have promised it 
who are infinitely powerful, faithful, kind, 
and merciful. 
In this hope I intend to live and die. 
Amen.

|Dómine Deus, spero per grátiam tuam
remissiónem ómnium peccatórum, 
et post hanc vitam ætérnam felicitátem 
me esse consecutúrum: 
quia tu promisísti, qui es infiníte 
potens, fidélis, benígnus, et miséricors.
In hac spe vívere et mori státuo.
Amen.
|=======

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Act of Love*|*Actus caritatis*
|O Lord God, I love you above all things 
and I love my neighbor for your sake 
because you are the highest, infinite and perfect
good, worthy of all my love. 
In this love I intend to live and die. 
Amen.

|Dómine Deus, 
amo te super ómnia 
et próximum meum propter te, 
quia tu es summum, infinítum, 
et perfectíssimum bonum, 
omni dilectióne dignum.
In hac caritáte 
vívere et mori státuo.
Amen.
|=======

 

[width="85%",style="verse",cols='.<, .<',options="header"]
|=======
|*Act of Contrition*|*Actus contritionis*
|O my God, I am heartily sorry for having offended Thee, and I detest all my
sins because of thy just punishments, but most of all because they offend Thee,
my God, who art all good and deserving of all my love. I firmly resolve with
the help of Thy grace to sin no more and to avoid the near occasion of sin.
Amen.

|Deus meus, ex toto corde pænitet me ómnium meórum peccatórum, éaque detéstor,
quia peccándo, non solum pœnas a te iuste statútas proméritus sum, sed
præsértim quia offéndi te, summum bonum, ac dignum qui super ómnia diligáris.
Ídeo fírmiter propóno, adiuvánte grátia tua, de cétero me non peccatúrum
peccandíque occasiónes próximas fugitúrum. Amen.
|=======
